name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bevane50/safina

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_vps:
    name: Pull and Run Docker Image on VPS
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: bevane/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          docker pull bevane50/safina
          docker stop safina
          docker rm safina
          docker run --name safina -d --network host -e PORT=3000 --env-file=".env.docker" -p 3000:3000 -p 7700:7700 bevane50/safina
          docker image prune
